#!/usr/bin/expect -f

set timeout 2
set mysql_temp_pass [lindex $argv 0]
set mysql_new_pass "2/XzS6atdd=h"

spawn mysql_secure_installation

expect "Enter password for user root:"

send "$mysql_temp_pass\r"

expect "New password:"

send "$mysql_new_pass\r"

expect "Re-enter new password:"

send "$mysql_new_pass\r"

expect "*any other key for No) :"

send "n\r"

expect "#"

send "n\r"

expect "#"

send "n\r"

expect "#"

send "n\r"

expect "#"

send "y\r"

expect eof