- name: Launch a new ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: cosimo2018key
    instance_type: t2.micro
    security_group: cosimo2018-sg
    image: ami-0e01ce4ee18447327
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-129a6779
        assign_public_ip: yes
        user_data: |
          #!/bin/bash -xe

          echo Installing nano, git
          yum install nano git -y

          echo installing php 7.3
          amazon-linux-extras install -y php7.3
          yum install php-bcmath php-mbstring php-xml php-gd php-gmp -y

          echo Installing apache
          yum install httpd -y
          touch /var/www/html/phpinfo.php
          echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php

          echo installing MySQL community edition
          yum install https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm -y
          yum install mysql-community-server -y
          systemctl enable mysqld
          systemctl start mysqld

          echo setting up website files
          cd /tmp
          git clone https://github.com/lijoyoung/cosimo2018.git
          cd cosimo2018
          unzip website.zip
          cd installable_file
          unzip dizzcox-v2.0.zip -d /var/www/html
          yum install mod_ssl -y

          systemctl enable httpd
          systemctl start httpd

          echo cleaning up
          rm -rf /tmp/*

          echo Installation complete
      register: ec2

    - name: Add the new instance to ansible hosts
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

# - name: Configure instance(s)
#   hosts: launched
#   become: True
#   gather_facts: True
#   roles:
#     - deploy_database
    